name: Deploy Production

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: CI & Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Debug SSH_VP_HOST
        run: |
            echo "Host recibido: '${{ secrets.SSH_VP_HOST }}'"

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" | tr -d '\r' > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan -H "${{ secrets.SSH_VP_HOST }}" >> ~/.ssh/known_hosts

      - name: Deploy via SSH
        run: |
          export SSH_AUTH_SOCK=""
          ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SSH_VP_HOST }} "
            cd /var/www/vhosts/mywallet.wpcache.es/httpdocs/my-wallet &&
            git pull origin main &&
            /opt/plesk/php/8.3/bin/php artisan config:cache &&
            /opt/plesk/php/8.3/bin/php artisan route:cache
          "
          