name: Deploy Production

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: CI & Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup SSH
        run: |
            mkdir -p ~/.ssh
            echo "${{ secrets.SSH_PRIVATE_KEY }}" | tr -d '\r' > ~/.ssh/id_ed25519_my_wallet
            chmod 600 ~/.ssh/id_ed25519_my_wallet
            ssh-keyscan -H mywallet.wpcache.es >> ~/.ssh/known_hosts
            echo "IdentityFile ~/.ssh/id_ed25519_my_wallet" >> ~/.ssh/config

      - name: Deploy via SSH
        run: |
          export SSH_AUTH_SOCK=""
          ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SSH_VP_HOST }} "
            cd /var/www/vhosts/mywallet.wpcache.es/httpdocs/my-wallet &&
            git pull origin main &&
            /opt/plesk/php/8.3/bin/php artisan config:cache &&
            /opt/plesk/php/8.3/bin/php artisan route:cache
          "
          